#use this when u trying to publify the db
FROM postgis/postgis:15-3.3

# Set the same environment variables as your docker-compose
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=2008
ENV POSTGRES_DB=clismabankend

# Copy your initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432